# 指定构建环境是Node.js，当前版本是稳定版
anguage: node_js
node_js: stable

env:
 global:
   - URL_REPO: github.com/xsomnus/blogs.git

# 设置钩子只检测blog-source分支的push变动
branches:
  only:
    - master

# 设置缓存文件
cache:
  directories:
    - node_modules
    
# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
  - hexo deploy
deploy: 
  provider: pages
  skip-cleanup: true 
  github-token: $GH_TOKEN 
  keep-history: true 
  on: 
    branch: master 
  local-dir: public
